version: '3'
services:
  
  # Servicio Nginx
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - apache

  # Servicio Apache 
  apache:
    # Utiliza la imagen más reciente de httpd (Apache HTTP Server)
    image: httpd:latest
    # Mapea el puerto 8081 de la máquina host al puerto 80 del contenedor Apache
    ports:
      - "8081:80"
    # Mapea los archivos de la pagina web al directorio htdocs del contenedor Apache
    volumes:
      - ./Frontend:/usr/local/apache2/htdocs/

  # Servicio MySQL
  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: proyectazo
      MYSQL_USER: sail
      MYSQL_PASSWORD: password

  XantiMetApi:
    image: markosmartinez/laravelpassport-php8.2
    container_name: XantiMetApi
    volumes:
      - ./LaravelApiPassport/:/var/www/html/ 
    ports:
      - 8082:8000
    depends_on:
      - mysql

  Feeder:
    image: markosmartinez/laravelpassport-php8.2
    container_name: Feeder
    volumes:
      - ./LaravelApi/:/var/www/html/
    ports:
      - 8085:8000
    command: ["sh", "-c", "php artisan app:import-municipios && php artisan schedule:work"]
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8083:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql